import { getBrowser } from "./pdfBrowser.js";
import { buildInvoiceHTML } from "../utils/invoicePdfTemplate.js";

const generateInvoicePdf = async (invoice) => {
  const html = buildInvoiceHTML(invoice);
  const browser = await getBrowser();

  const context = await browser.newContext();
  const page = await context.newPage();

  try {
    await page.setContent(html, {
      waitUntil: "domcontentloaded",
    });
    await page.emulateMedia({
      media: "print",
    });
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: "<span></span>",
      footerTemplate: `
        <div style="width:100%;text-align:center;font-size:10px;color:#6b7280;font-family:Helvetica,Arial,sans-serif;">
          Generated by FAB Five Network Billing System
        </div>
      `,
      margin: {
        top: "24px",
        bottom: "40px",
        left: "24px",
        right: "24px",
      },
    });

    const safeFileName = `${invoice.invoiceNumber}`.replace(/[<>:"/\\|?*]/g, "-");

    return {
      buffer: pdfBuffer,
      mimeType: "application/pdf",
      fileName: `${safeFileName || "Invoice"}.pdf`,
    };
  } finally {
    await page.close();
    await context.close();
  }
};

export default generateInvoicePdf;